language: go
go: '1.10.x'

before_install:
  - npm install -g tiddlywiki

install:
- echo "Skip default install"

script:
- tiddlywiki ./docs/wiki --verbose --output ./docs/wikiout --build


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./docs/wikiout
  on:
    branch: master
